### ISSUE TITLE
JSON object issue

### ISSUE THREAD

**Issue by Kirashite** [Kenan2000/Secronom-Zombies#52]
Encountered a problem, during character creation/world first start. Namely: after the error in file secro_eoc.json world terminates and returns to main menu. On the screenshots attached below you can see the list of my installed mods(maybe it will help) and problem itself(error with PETFOOD isn't critical, but still).
![Screenshot_1](https://user-images.githubusercontent.com/123884367/215493145-093cef27-18c4-4436-9ae9-f84206671ecd.png)
![Screenshot_2](https://user-images.githubusercontent.com/123884367/215493155-020854ac-dae3-4761-aaa8-2b9e3ef811ad.png)
![Screenshot_3](https://user-images.githubusercontent.com/123884367/215493159-7bee9913-b0ab-466a-9484-8c13fe5fdcd3.png)

**Comment by Kenan2000** [comment]
@Kirashite All of these errors, both petfood along with eoc not being recognized is because you use an older version of game, both petfood along with eoc exist in latest experimental versions. Either this or it's because you use a launcher to download mods which likely has installed an incompatible version of mod. Use launcher only to update game itself, whereas download mods manually via GitHub, this is true for mods of other authors along with mods in my or my Modpack hopefully as well

**Comment by Kirashite** [comment]
@Kenan2000 Yeah, thanks, found previous issue threads and found myself installing experimental version. Nevertheless, thanks.

**Comment by Kenan2000** [comment]
@Kirashite No problem
