### ISSUE TITLE
Unable to create a world with this mod because  of an error.

### ISSUE THREAD

**Issue by throwawya** [Kenan2000/Secronom-Zombies#72]
Cant create a world with this mod because of a error.
Error message:
 DEBUG    : Error: Json error: storage/emulated/0/Android/data/com.cleverraven.cataclysmdda/files/data/mods/cleverravensecronom/Modification_Files/Items/-Essentials/secro_mat.json:1:2: missing mandatory member "bash_resist"

[
 ^
  {
    "type": "material",
    "id": "secro_null",

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : C:/Projects/Cataclysm-DDA/android/app/jni/src/../../../../src/main_menu.cpp
 LINE     : 986
 VERSION  : 0.G

**Comment by throwawya** [comment]
Dont ask why I named the mod like that, I dont really know why too to be honest.

**Comment by Kenan2000** [comment]
So all mods which I try to maintain hopefully for CDDA are for latest experimental versions with me having no interest, no motivation, putting no effort into wanting to add support for stable versions for them, as it is stated in all README files on GitHub on each of my repositories for CDDA mods if you did not read that including for Axema's mod, rightful sole Secronom author, which I only try to maintain hopefully with me having no claims on authorship of his work, because Secronom is entirely Axema's mod honestly. If you want to play with them you need to download latest experimental versions
